### PR TITLE
fix: load file-loader output filename

### LINKED ISSUE #85: file-loader generates unexpected pages
Hi.

I'm trying to use `` with fusuma and found this issue.

f3ca896531d66c2578ec0ea69388a808

The markdown of the above slides is so simple : 

```markdown
<img src="logo.svg" />
```

But the build presentation displays filehash name... 🤔

### PR DESCRIPTION
**Pull request by Quramy**
fix #85

### CODE REVIEW

File: src/client/src/index.js [hunk 1]
```diff
@@ -8,14 +8,14 @@ import './setup/css';
 // }
 
 (async () => {
-  const slidesInfo = fetchSlides(require.context(process.env.SLIDE_PATH));
+  const slidesInfo = fetchSlides(require.context(process.env.SLIDE_PATH, false, /\.md$/));
```
Comment (Quramy) [inline src/client/src/index.js]: I think files that file-loader emits causes #86 and we need only "*.md" files to crate `slidesInfo`. How about this?

Comment (hiroppy) [reply src/client/src/index.js]: Good catch! You're right.
